name: Deploy to Server
on:
    push:
        branches:
            - production
jobs:
    build:
        name: Build and upload to server
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js 20
              uses: actions/setup-node@v2
              with:
                  node-version: "20.0.0"
                  cache: "yarn"
                  cache-dependency-path: "app/yarn.lock"
            - run: yarn build:app
            - name: Copy folder content recursively to server
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: app/build
                  remote: /var/www/html/zktax/build
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  rmRemote: true
